import type { JobListResponse } from "../types/job";

export const MOCK_JOBS: JobListResponse = {
  jobs: [
    {
      id: "mock-1",
      title: "프론트엔드 개발자",
      company: "카카오",
      location: "서울 성동구",
      experience: "경력 1년 이상",
      employment_type: "정규직",
      is_active: true,
      crawled_at: new Date().toISOString(),
      sources: [{ id: "s1", source: "wanted", url: "https://www.wanted.co.kr/wd/1" }],
    },
    {
      id: "mock-2",
      title: "백엔드 개발자 (Python/FastAPI)",
      company: "토스",
      location: "서울 강남구",
      experience: "신입",
      employment_type: "정규직",
      is_active: true,
      crawled_at: new Date().toISOString(),
      sources: [
        { id: "s2", source: "wanted", url: "https://www.wanted.co.kr/wd/2" },
        { id: "s3", source: "linkareer", url: "https://linkareer.com/recruit/2" },
      ],
    },
    {
      id: "mock-3",
      title: "풀스택 개발자 (React + Node.js)",
      company: "당근마켓",
      location: "재택/원격",
      experience: "경력무관",
      employment_type: "정규직",
      is_active: true,
      crawled_at: new Date().toISOString(),
      sources: [{ id: "s4", source: "jasoseol", url: "https://jasoseol.com/job/3" }],
    },
    {
      id: "mock-4",
      title: "iOS 개발자",
      company: "네이버",
      location: "경기 성남시",
      experience: "경력 3년 이상",
      employment_type: "정규직",
      is_active: true,
      crawled_at: new Date().toISOString(),
      sources: [{ id: "s5", source: "catch", url: "https://www.catch.co.kr/4" }],
    },
    {
      id: "mock-5",
      title: "데이터 엔지니어",
      company: "쿠팡",
      location: "서울 송파구",
      experience: "경력 2년 이상",
      employment_type: "정규직",
      is_active: true,
      crawled_at: new Date().toISOString(),
      sources: [{ id: "s6", source: "groupby", url: "https://www.groupby.kr/5" }],
    },
    {
      id: "mock-6",
      title: "Android 개발자 (인턴)",
      company: "라인플러스",
      location: "서울 강남구",
      experience: "인턴",
      employment_type: "인턴",
      is_active: true,
      crawled_at: new Date().toISOString(),
      sources: [{ id: "s7", source: "wanted", url: "https://www.wanted.co.kr/wd/6" }],
    },
  ],
  total: 6,
  page: 1,
  size: 20,
  has_next: false,
};
